# --- Базовые настройки ---
baseURL = 'https://xak3r.github.io/project-practice/'
locale = 'ru-RU'
title = 'POLI-STUDIO'
# theme = 'compose'

# --- Параметры темы Compose ---
[params]
  description = "Короткие видео о главном. Мы снимаем ролики, чтобы показать жизнь университета и привлечь талантливых абитуриентов."
  author = "POLI-STUDIO team"
  featured_video = "https://www.youtube.com/embed/dQw4w9WgXcQ"

# --- Меню сайта ---
[[menu.main]]
  name = "Главная"
  url = "/"
  weight = 1

[[menu.main]]
  name = "О проекте"
  url = "/about/"
  weight = 2

[[menu.main]]
  name = "Команда"
  url = "/team/"
  weight = 3

[[menu.main]]
  name = "Журнал"
  url = "/posts/"
  weight = 4

[[menu.main]]
  name = "Ресурсы"
  url = "/resources/"
  weight = 5

[[menu.main]]
  name = "Тест"
  url = "/quiz/"
  weight = 6